apiVersion: v1
kind: PersistentVolumeCLaim
metadata:
    name: mysql-dados
spec:
    acessModes:
        - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: standard-rwo
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    selector: 
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - image: robertocosta007/projeto-database:1.0
                    args:
                    -  "--ignore-db-dir=lost+found"
                    imagePullPolicy: Always
                    name: mysql
                    ports:
                    -  containerPort: 3306
                        name: mysql
                    volumeMounts:
                    - name: mysql-dados
                      moutPath: /var/lib/mysql/
            volumes:
                - name: mysql-dados
                  persistentVolumeClaim:
                    claimName: mysql-dados
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: php
    labels:
        app: php
spec:
    replicas: 6
    selector: 
        matchLabels:
            app: php
    template:
        metadata:
          labels:
            app: php
        spec:
            containers:
               name: php
               image: robertocosta007/projeto-backend:1.0
               imagemPullPolicy: Always
               ports:
                containerPort: 80